const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const CLEAR_USER_INPUTS = "CLEAR_USER_INPUTS";
const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
const FETCH_REGISTER_USER_REQUEST = "FETCH_REGISTER_USER_REQUEST";
const FETCH_REGISTER_USER_SUCCESS = "FETCH_REGISTER_USER_SUCCESS";
const FETCH_REGISTER_USER_FAILURE = "FETCH_REGISTER_USER_FAILURE";
const DELETE_ERROR = 'DELETE_ERROR'
export default {
  LOGIN_USER,
  DELETE_ERROR,
  LOGOUT_USER,
  CHANGE_INPUT_VALUE,
  FETCH_USER_FAILURE,
  FETCH_USER_REQUEST,
  FETCH_USER_SUCCESS,
  CLEAR_USER_INPUTS,
  FETCH_REGISTER_USER_FAILURE,
  FETCH_REGISTER_USER_REQUEST,
  FETCH_REGISTER_USER_SUCCESS,
};
