const ADD_ITEM_TO_BUCKET = "ADD_ITEM_TO_BUCKET";
const DELETE_ITEM_FROM_BUCKET = "DELETE_ITEM_FROM_BUCKET";
const SET_ELEMENT_TO_DELETE = "SET_ELEMENT_TO_DELETE";
const TOGGLE_ELEMENT_TO_PAY = "TOGGLE_ELEMENT_TO_PAY";
const SAVE_FETCHED_BUCKET = "SAVE_FETCHED_BUCKET";
const FETCH_BUCKET_REQUEST = "FETCH_BUCKET_REQUEST";
const FETCH_BUCKET_SUCCESS = "FETCH_BUCKET_SUCCESS";
const FETCH_BUCKET_FAILURE = "FETCH_BUCKET_FAILURE";
const CLEAR_BUCKET = 'CLEAR_BUCKET'; 
export default {
  ADD_ITEM_TO_BUCKET,
  DELETE_ITEM_FROM_BUCKET,
  SET_ELEMENT_TO_DELETE,
  FETCH_BUCKET_FAILURE,
  TOGGLE_ELEMENT_TO_PAY,
  FETCH_BUCKET_REQUEST,
  SAVE_FETCHED_BUCKET,
  FETCH_BUCKET_SUCCESS,
  CLEAR_BUCKET
};
