const ADD_ESPRESSO = "ADD_ESPRESSO";
const ADD_MILK = "ADD_MILK";
const ADD_WATER = "ADD_WATER";
const DELETE_ESPRESSO = "DELETE_ESPRESSO";
const DELETE_MILK = "DELETE_MILK";
const DELETE_WATER = "DELETE_WATER";
const TOGGLE_CHOCOLATE = "TOGGLE_CHOCOLATE";
const SET_PRESET_OF_COFFEE = "SET_PRESET_OF_COFFEE";
const SET_LAT_LNG = "SET_LAT_LNG";
const SET_ORDER_ADRESS= 'SET_ORDER_ADRESS'
const CLEAR_ORDER  = 'CLEAR_ORDER'
export default {
  ADD_ESPRESSO,
  TOGGLE_CHOCOLATE,
  ADD_MILK,
  ADD_WATER,
  DELETE_ESPRESSO,
  DELETE_MILK,
  DELETE_WATER,
  SET_PRESET_OF_COFFEE,
  SET_LAT_LNG,
  SET_ORDER_ADRESS,
  CLEAR_ORDER
};
